nvim-zshrc-passwordsync

diff --git a/.local/bin/base-config/passwordsync b/.local/bin/base-config/passwordsync
--- a/.local/bin/base-config/passwordsync
+++ b/.local/bin/base-config/passwordsync
@@ -1,16 +1,24 @@
 #!/usr/bin/env sh
 
-partition=/dev/sdb1
-
-if [ -b "$partition" ] && ! /usr/binfindmnt "$partition" > /dev/null 2>&1; then
-	echo "$partition exists"
-	src=/mnt/.database.kdbx
-	dest=/home/daniel/.local/share/daniel/database.kdbx
-	/usr/bin/sudo /bin/mount /dev/sdb1 /mnt
-	/usr/bin/findmnt "$partition"
-	/usr/bin/sudo /bin/cp -v "$src" "$dest"
-	/usr/bin/sudo /bin/chmod -v 600 "$dest"
-	/usr/bin/sudo /bin/chown -v daniel:daniel "$dest"
-else
-	echo "$partition does not exist or it is already mounted"
+if [ -z "$2" ] || ! echo "$2" | grep -q '.*\.kdbx'; then
+    echo "Provide a path to a keepassxc database"
+    exit 1
 fi
+
+local_path="$2"
+remote_dir=~/keepass
+db_name=$(basename "$2")
+server="daniel@192.168.1.1"
+
+case "$1" in
+'pull')
+    rsync "${server}:${remote_dir}/${db_name}" "$local_path"
+    ;;
+'push')
+    rsync "$local_path" "${server}:${remote_dir}/${db_name}"
+    ;;
+*)
+    echo "Invalid option. Use 'pull' or 'push'."
+    exit 1
+    ;;
+esac
